// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1eGJezqLyQ83P7pdlLsF0Ecaq5JrX8hI',
    appId: '1:971914231376:web:6d1c299960494457ce1b55',
    messagingSenderId: '971914231376',
    projectId: 'clarity-d3d92',
    authDomain: 'clarity-d3d92.firebaseapp.com',
    storageBucket: 'clarity-d3d92.firebasestorage.app',
    measurementId: 'G-PBG7QY8DW1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzjl0IHfX-4ZU_L7HahI6-LmVCQkDWOHc',
    appId: '1:971914231376:android:fc56217a71a611c4ce1b55',
    messagingSenderId: '971914231376',
    projectId: 'clarity-d3d92',
    storageBucket: 'clarity-d3d92.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCs5FPPDrkd16I-ZkJfF6hfXdkLHJAAJck',
    appId: '1:971914231376:ios:2f13adb1f3766889ce1b55',
    messagingSenderId: '971914231376',
    projectId: 'clarity-d3d92',
    storageBucket: 'clarity-d3d92.firebasestorage.app',
    androidClientId: '971914231376-6s8h8iegm28r3lv284m01mvc8cbe8kuq.apps.googleusercontent.com',
    iosClientId: '971914231376-urosmrtul7htbimrbjh65sg8hic8nfcq.apps.googleusercontent.com',
    iosBundleId: 'com.example.clarity',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCs5FPPDrkd16I-ZkJfF6hfXdkLHJAAJck',
    appId: '1:971914231376:ios:2f13adb1f3766889ce1b55',
    messagingSenderId: '971914231376',
    projectId: 'clarity-d3d92',
    storageBucket: 'clarity-d3d92.firebasestorage.app',
    iosClientId: '971914231376-urosmrtul7htbimrbjh65sg8hic8nfcq.apps.googleusercontent.com',
    iosBundleId: 'com.example.clarity',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1eGJezqLyQ83P7pdlLsF0Ecaq5JrX8hI',
    appId: '1:971914231376:web:4cb7de1e8661467ece1b55',
    messagingSenderId: '971914231376',
    projectId: 'clarity-d3d92',
    authDomain: 'clarity-d3d92.firebaseapp.com',
    storageBucket: 'clarity-d3d92.firebasestorage.app',
    measurementId: 'G-13D29H5PNX',
  );
}
