import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'core/di/injection_container.dart' as di;
import 'core/router/app_router.dart';
import 'core/theme/app_theme.dart';
import 'core/config/env_config.dart';
import 'core/services/notification_service.dart';
import 'features/settings/presentation/bloc/settings_bloc.dart';
import 'features/auth/domain/repositories/auth_repository.dart';
import 'features/auth/presentation/bloc/auth_bloc.dart';
import 'core/utils/localizer.dart';
import 'firebase_options.dart'; // GENERATED by `flutterfire configure`
import 'package:intl/date_symbol_data_local.dart';

/// Handles messages received while the app is backgrounded/terminated. Runs in
/// its own isolate, so it must initialize Firebase itself. The OS displays
/// notification-payload messages in the system tray automatically.
@pragma('vm:entry-point')
Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
}

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await initializeDateFormatting(); // Initialize localized date formatting
  // Initialize Firebase before any FirebaseAuth / Messaging usage.
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  FirebaseMessaging.onBackgroundMessage(_firebaseMessagingBackgroundHandler);
  final envConfig = await EnvConfig.load();
  await di.init(envConfig);
  await Localizer.init();
  await _ensureSignedIn();
  await di.sl<NotificationService>().initialize();
  runApp(const MyApp());
}

/// Guarantees the app always has a uid before anything writes user-scoped data.
///
/// FCM token documents and saved cities are both keyed by uid and their
/// Firestore rules require ownership, so a signed-out device could neither
/// register for alerts nor bookmark a city. Anonymous sign-in is silent, free,
/// and upgradeable in place from the profile — linking preserves the uid, so
/// nothing is orphaned when the user later attaches a real account.
Future<void> _ensureSignedIn() async {
  final auth = di.sl<AuthRepository>();
  if (auth.currentUser != null) return;
  // Best-effort: a first launch with no network must still open the app. The
  // next launch (or any sign-in) picks it up.
  final result = await auth.signInAnonymously();
  result.fold(
    (failure) => debugPrint('Anonymous sign-in unavailable: ${failure.message}'),
    (_) {},
  );
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MultiBlocProvider(
      providers: [
        BlocProvider(create: (context) => di.sl<SettingsBloc>()),
        // App-wide auth state — subscribes to FirebaseAuth on creation.
        BlocProvider(create: (context) => di.sl<AuthBloc>()),
      ],
      child: BlocBuilder<SettingsBloc, SettingsState>(
        builder: (context, state) {
          return MaterialApp.router(
            title: 'Clarity Weather',
            debugShowCheckedModeBanner: false,
            theme: AppTheme.lightTheme,
            themeMode: ThemeMode.light, // Locked to Light Mode
            // Lets NotificationService show foreground alerts as in-app SnackBars.
            scaffoldMessengerKey: di.sl<NotificationService>().messengerKey,
            routerConfig: AppRouter.router,
          );
        },
      ),
    );
  }
}
